<h3><center>Creating Arrays One and Two dimensions</center></h3>

In [1]:
# Importing package numpy
import numpy as np

In [2]:
arr1 = np.eye(4, 4) # Creating array with ones on the diagonal
arr2 = np.eye(4, 4, k=1) # Creating array with ones on the diagonal, k represents the column
arr3 = np.diag((2, 4, 6, 8)) # Creating array with values on the diagonal
arr4 = np.ones(2) # Creating array with ones
arr5 = np.zeros((2, 2)) # Creating array of zeros

In [3]:
# Identity array
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
# Identity array with k parameter
arr2

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [5]:
# Array with diag
arr3

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [6]:
# Array of ones
arr4

array([1., 1.])

In [7]:
# Two-dimensional array of zeros
arr5

array([[0., 0.],
       [0., 0.]])

In [8]:
# Using tile in order to multiply the structure (row or column)
arr6 = np.array([[1,2], [3, 4]])

# Column
np.tile(arr6, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [9]:
# Row
np.tile(arr6, (2, 2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])