<h3><center>Using random in numpy</center></h3>

In [1]:
# Importing package numpy
import numpy as np

In [2]:
# Pseudo-random number generators it's good for testing
np.random.seed(0)

In [3]:
# Using functions for generate
np.random.randint(4, size=4)

array([0, 3, 1, 0])

In [4]:
# Pseudo-random number generators it's good for testing
np.random.seed(0)

In [5]:
# Take a look at that the numbers are the same
np.random.randint(4, size=4)

array([0, 3, 1, 0])

In [6]:
# Creating array with a uniform distribution 
np.random.rand(10, 2)

array([[0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ],
       [0.96366276, 0.38344152],
       [0.79172504, 0.52889492],
       [0.56804456, 0.92559664],
       [0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985],
       [0.77815675, 0.87001215],
       [0.97861834, 0.79915856]])

In [7]:
# Creating array with a normal distribution
np.random.randn(10, 2)

array([[ 1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252],
       [-0.88778575, -1.98079647],
       [-0.34791215,  0.15634897]])

<h3><center>Operations with arrays</center></h3>

In [2]:
# Creating arry with step
arr1 = np.arange(0, 10, 2)
# Multiply the numbers by the value
arr2 = np.arange(5) * 2

In [3]:
# Print arr1
arr1

array([0, 2, 4, 6, 8])

In [4]:
# Print arr2
arr2

array([0, 2, 4, 6, 8])

In [5]:
# Sum of arrays
arr1 + arr2

array([ 0,  4,  8, 12, 16])

In [6]:
# Working with bool elements
np.logical_and(True, True) and np.logical_not(False)

True

In [8]:
# Simple operations
arr1.mean()

4.0

In [9]:
arr1.std()

2.8284271247461903

In [10]:
arr1.min()

0

In [11]:
arr1.max()

8

In [12]:
arr1.sum()

20

In [13]:
# Saving array
np.save('data', arr1)
load = np.load('data.npy')

In [14]:
load

array([0, 2, 4, 6, 8])