In [7]:
# Importing package numpy
import numpy as np

In [2]:
# Creating array
arr1 = np.array([1, 2, 3, 4])

In [3]:
# Returning the first position
arr1[0]

1

In [4]:
# Returning the last position
arr1[-1]

4

In [5]:
# Returning all elements make stepping
arr1[::2]

array([1, 3])

In [6]:
# Returning all elements starting at index 1
arr1[1:]

array([2, 3, 4])

In [7]:
# Returning all elements make stepping
arr1[::-1]

array([4, 3, 2, 1])

In [19]:
# Returning elements with exclusive
arr1[0:4:2]

array([1, 3])

In [8]:
# Creating two-dimensional array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [14]:
# Priting...
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# The rule is: undestand the dimension you are
arr2[1, 2]

6

In [10]:
# Returning another element (in this case: row)
arr2[1]

array([4, 5, 6])

In [12]:
# Otherwise...#bestway 
arr2[1,]

array([4, 5, 6])

In [13]:
# Returning all elements of column index 0
arr2[:, 0]

array([1, 4])

In [15]:
# Returning all elements of row index 1 on each column
arr2[1, :]

array([4, 5, 6])

In [21]:
# Filling out the array with zeros
arr2[1, :] = np.zeros(3); arr2

array([[1, 2, 3],
       [0, 0, 0]])

In [22]:
# Subset example
arr3 = arr2[1, :]

In [23]:
# Priting....
arr3

array([0, 0, 0])

In [24]:
# Otherwise...
arr4 = arr3.copy()

In [25]:
# Priting...
arr4

array([0, 0, 0])

In [ ]:
# Creating two-dimensional array
x = np.array([[1, 2], [3, 4], [5, 6]])

In [39]:
# Priting...
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
# Transpose
x.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [42]:
# Either...
np.transpose(x)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [59]:
# Advanced indexing it's really really useful
y = np.array([[ 1,  2,  3],
              [ 4,  5,  6],
              [ 7,  8,  9],
              [ 10, 11, 12]])

rows = np.array([[0, 0],
                  [3, 3]], dtype=np.intp)

columns = np.array([[0, 0],
                    [0, 0]], dtype=np.intp)

In [60]:
# In this case see the output
y[rows]

array([[[ 1,  2,  3],
        [ 1,  2,  3]],

       [[10, 11, 12],
        [10, 11, 12]]])

In [61]:
# Okay, so let's it
y[rows, columns]

array([[ 1,  1],
       [10, 10]])

In [72]:
# Other thing important: Broadcasting
z = np.array([[1, 2, 3, 4]])

In [73]:
# Printing...
z.T

array([[1],
       [2],
       [3],
       [4]])

In [77]:
# Are you remember the high scholl?
z.T + z

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [79]:
# And finally...Converting to array
np.ravel(z.T + z)

array([2, 3, 4, 5, 3, 4, 5, 6, 4, 5, 6, 7, 5, 6, 7, 8])

In [82]:
# Ops... One-dimensional array to Two-dimensional array
arr1.reshape(2, 2)

array([[1, 2],
       [3, 4]])

In [96]:
# We can also order the array
np.sort(y, axis=1) # By row -> 1 or column -> 0

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [97]:
# Let's go to check a value, a good option to verify missing values, okay?
np.all(arr1 > 0)

True

In [98]:
# Yeah
np.any(arr1 == 0)

False

In [23]:
# Array to Matrix
conversion = np.asarray(np.mat([[1, 2], [3, 4]]))

In [24]:
# New matrix
conversion

array([[1, 2],
       [3, 4]])

In [25]:
# The difference between matrix and array
matrix = np.mat([[1, 2], [3, 4]])
dif = np.array([[1, 2], [3, 4]]); mat

matrix([[1, 2, 3],
        [4, 5, 6]])

In [19]:
# Array 2 ndim
dif

array([[1, 2],
       [3, 4]])

In [20]:
# Multiply matrix, the methods and attributes are differents
matrix * matrix

matrix([[ 7, 10],
        [15, 22]])

In [21]:
# Multply array
dif * dif

array([[ 1,  4],
       [ 9, 16]])

In [22]:
# But, we can try.....yes, the same result above
np.dot(dif, dif)

array([[ 7, 10],
       [15, 22]])